name: CMake windows

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Install GIT
      shell: powershell
      run: Install-Module posh-git -Scope CurrentUser -Force
    
    - uses: actions/checkout@v2
    
    - name: Clone repos
      shell: powershell
      run: |
       git clone https://github.com/xmrig/xmrig.git
       git clone https://github.com/xmrig/xmrig-deps.git
    
    - uses: msys2/setup-msys2@v2
    
    - shell: powershell
      run: | 
       msys2 -c 'pacman -Syu'
       msys2 -c 'uname -a'
       



