name: CMake windows

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2
    
    - name: Install GIT
      shell: powershell
      run: Install-Module posh-git -Scope CurrentUser -Force
    
    - name: Clone repos
      shell: powershell
      run: |
       git clone https://github.com/xmrig/xmrig.git
       git clone https://github.com/xmrig/xmrig-deps.git
    
    - uses: msys2/setup-msys2@v2
    
    - shell: powershell
      run: msys2 -c 'pacman -Syu'
    - shell: powershell
      run: msys2 -c 'Y | pacman -S mingw-w64-x86_64-gcc git make'
    - shell: powershell
      run: msys2 -c 'mkdir xmrig/build && cd xmrig/build'
    - shell: powershell
      run: msys2 -c 'cmake .. -G "Unix Makefiles" -DXMRIG_DEPS=c:/xmrig-deps/gcc/x64'
