name: CMake windows

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2
    
    - name: Install GIT
      shell: powershell
      run: Install-Module posh-git -Scope CurrentUser -Force
    
    - name: Install choco
      shell: powershell
      run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

    - shell: powershell
      run: choco feature enable -n allowGlobalConfirmation
      
    - shell: powershell
      run: choco install cmake -y --installargs 'ADD_CMAKE_TO_PATH=System'
    
    - shell: powershell
      run: refreshenv
    
    - name: Clone repos
      shell: powershell
      run: |
       git clone https://github.com/xmrig/xmrig.git
       git clone https://github.com/xmrig/xmrig-deps.git
    
    - uses: msys2/setup-msys2@v2
    
    - shell: powershell
      run: msys2 -c 'pacman -Syu --noconfirm'
    - shell: powershell
      run: msys2 -c 'pacman -S mingw-w64-x86_64-gcc git make  --noconfirm'
    - shell: powershell
      run: msys2 -c 'mkdir xmrig/build && cd xmrig/build'
    - shell: msys2 {0}
      run: |
       uname -a
       'C:\Program Files\CMake\bin\cmake.exe' .. -G "Unix Makefiles" -DXMRIG_DEPS=../../xmrig-deps/gcc/x64

