name: CMake

on:
  release:
    # Solo usa la palabra clave de tipos para reducir los tipos de actividad que activarán tus flujos de trabajo.
    types: [published, created, edited]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: INstall 
      run: sudo apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
      
    - name: Clone
      run: git clone https://github.com/xmrig/xmrig.git
      
    - name: make
      run: |
        mkdir xmrig/build && cd xmrig/build
        cmake ..
        make -j$(nproc)


